// app/globalState.ts

export type Language = 'si' | 'en' | 'ta';

export const translations = {
  si: {
    govTitle: "ප්‍රාදේශීය සභා සේවක ද්වාරය",
    govSub: "රාජ්‍ය සේවා ජංගම පද්ධතිය",
    loginTitle: "ප්‍රාදේශීය සභා සේවක කළමනාකරණය",
    epfLabel: "EPF / සේවක අංකය",
    passLabel: "මුරපදය (Password)",
    loginBtn: "පද්ධතියට ඇතුළු වන්න",
    welcome: "ආයුබෝවන්",
    dept: "ප්‍රජා සංවර්ධන අංශය",
    menu1: "නිවාඩු ශේෂය",
    menu2: "පැමිණිලි ඉදිරිපත් කිරීම",
    menu3: "පොදු නිවේදන",
    menu4: "මගේ පැතිකඩ",
    profileTitle: "මගේ තොරතුරු",
    role: "පුස්තකාල සහ පෙරපාසල් සහකාර",
    editProfile: "පැතිකඩ සංස්කරණය",
    updateBtn: "තොරතුරු යාවත්කාලීන කරන්න",
    saveBtn: "වෙනස්කම් සුරකින්න",
    phoneLabel: "දුරකථන අංකය",
    casual: "අනියම් නිවාඩු",
    medical: "වෛද්‍ය නිවාඩු",
    duty: "රාජකාරිමය నిවාඩු",
    newLeave: "නව නිවාඩු ඉල්ලීමක්",
    leaveStatus: "කලින් දැමූ ඉල්ලීම්වල තත්ත්වය",
    reason: "හේතුව සඳහන් කරන්න",
    submit: "ඉදිරිපත් කරන්න",
    approved: "අනුමතයි",
    digitalForm: "ඩිජිටල් නිවාඩු පෝරමය",
    signBtn: "ඩිජිටල් අත්සන තැබීම",
    signDesc: "ඔබගේ සම්පූර්ණ නම ටයිප් කර අත්සන තහවුරු කරන්න",
    complaintLabel: "පැමිණිල්ලේ විස්තරය",
    replied: "පිළිතුරු ලබාදී ඇත",
    notiTitle: "දැනුම්දීම්",
  },
  en: {
    govTitle: "Pradeshiya Sabha Portal",
    govSub: "Local Government Staff System",
    loginTitle: "Staff Management System",
    epfLabel: "EPF / Service Number",
    passLabel: "Password",
    loginBtn: "Secure Login",
    welcome: "Welcome",
    dept: "Praja Development Section",
    menu1: "Leave Management",
    menu2: "Submit Complaints",
    menu3: "Announcements",
    menu4: "My Profile",
    profileTitle: "My Profile Details",
    role: "Library & Preschool Assistant",
    editProfile: "Edit Profile",
    updateBtn: "Update Contact Info",
    saveBtn: "Save Changes",
    phoneLabel: "Contact Number",
    casual: "Casual Leave",
    medical: "Medical Leave",
    duty: "Duty Leave",
    newLeave: "Apply New Leave",
    leaveStatus: "Track Leave Status",
    reason: "State Your Reason",
    submit: "Submit Application",
    approved: "Approved",
    digitalForm: "Digital Leave Form",
    signBtn: "Proceed to Sign",
    signDesc: "Type your full name to electronically sign",
    complaintLabel: "Complaint Details",
    replied: "Replied",
    notiTitle: "Notifications",
  },
  ta: {
    govTitle: "பிரதேச சபை ஊழியர் போர்டல்",
    govSub: "உள்ளூர் அரசு ஊழியர் அமைப்பு",
    loginTitle: "ஊழியர் மேலாண்மை அமைப்பு",
    epfLabel: "EPF / ஊழியர் எண்",
    passLabel: "கடவுச்சொல்",
    loginBtn: "உள்நுழைக",
    welcome: "வரவேற்கிறோம்",
    dept: "பிரஜா மேம்பாட்டு பிரிவு",
    menu1: "விடுமுறை மேலாண்மை",
    menu2: "புகார்களை சமர்ப்பிக்க",
    menu3: "அறிவிப்புகள்",
    menu4: "எனது சுயவிவரம்",
    profileTitle: "சுயவிவர விவரங்கள்",
    role: "நூலகம் மற்றும் முன்பள்ளி உதவியாளர்",
    editProfile: "சுயவிவரத்தை திருத்தவும்",
    updateBtn: "தகவலைப் புதுப்பிக்கவும்",
    saveBtn: "மாற்றங்களைச் சேமிக்கவும்",
    phoneLabel: "தொலைபேசி எண்",
    casual: "தற்செயல் விடுப்பு",
    medical: "மருத்துவ விடுப்பு",
    duty: "கடமை விடுப்பு",
    newLeave: "புதிய விடுப்புக்கு விண்ணப்பிக்கவும்",
    leaveStatus: "விடுப்பு நிலையை கண்காணிக்கவும்",
    reason: "காரணத்தைக் குறிப்பிடவும்",
    submit: "சமர்ப்பிக்கவும்",
    approved: "அங்கீகரிக்கப்பட்டது",
    digitalForm: "டிஜிட்டல் விடுப்பு படிவம்",
    signBtn: "கையெழுத்திட செல்லுங்கள்",
    signDesc: "மின்னணு கையொப்பமிட உங்கள் முழு பெயரை உள்ளிடவும்",
    complaintLabel: "புகார் விவரங்கள்",
    replied: "பதில் அளிக்கப்பட்டது",
    notiTitle: "அறிவிப்புகள்",
  }
};